### ISSUE TITLE
 java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 12 (in Android)

### ISSUE THREAD

**Issue by chancyWu** [casbin/jcasbin#212]
Hi Guys,

I'm using this jcasbin in android to parse the model and policies. But when i try to run the enforce(sub, obj, act), it will throw the  ExceptionInInitializerError

```
java.lang.ExceptionInInitializerError
        at org.casbin.jcasbin.util.BuiltInFunctions.keyMatch3(BuiltInFunctions.java:96)
        at ....
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 12
    (.*)\{[^/]+}(.*)
                ^
        at com.android.icu.util.regex.PatternNative.compileImpl(Native Method)
        at com.android.icu.util.regex.PatternNative.<init>(PatternNative.java:39)
        at com.android.icu.util.regex.PatternNative.create(PatternNative.java:35)
        at java.util.regex.Pattern.compile(Pattern.java:1426)
        at java.util.regex.Pattern.<init>(Pattern.java:1401)
        at java.util.regex.Pattern.compile(Pattern.java:959)
        at org.casbin.jcasbin.util.BuiltInFunctions.<clinit>(BuiltInFunctions.java:36)
```

It's due to the BuiltInFunctions, the patterns used didn't add escape for the closing }.  Besides keyMatch3Pattern, the keyMatch4 there is also one regex pattern didn't add the escape for the closing }.  In normal Java JVM, the regex engine supports this no escape for the closing }, but the android JVM regex engine is [ICU Engine](http://userguide.icu-project.org/strings/regexp) ,  which requires both { and } that represent literal open/close curly braces must be escaped in ICU regex patterns.  some details can also refer to [this question](https://stackoverflow.com/questions/45074813/regex-pattern-error-in-android-when-matching-closing-brace)

Can we also support the ICU regex to support the android? .

**Comment by hsluoyz** [comment]
Hi @chancyWu , is there a way to support both general Java and Android? If yes, can you make a PR to fix it?

**Comment by chancyWu** [comment]
@hsluoyz I added the \\ for the closing` }` in the PR. This can support both general Java and Android.
