### ISSUE TITLE
java.lang.UnsupportedOperationException: can't load this type of class file (in android)

### ISSUE THREAD

**Issue by chancyWu** [casbin/jcasbin#214]
When i use the enforce(sub, obj, act) in android, there will be some Error thrown from the aviator. 
Detailed log is as below:

```
java.lang.ExceptionInInitializerError
        at com.googlecode.aviator.AviatorEvaluator$StaticHolder.access$000(AviatorEvaluator.java:90)
        at com.googlecode.aviator.AviatorEvaluator.getInstance(AviatorEvaluator.java:101)
        at com.googlecode.aviator.AviatorEvaluator.<clinit>(AviatorEvaluator.java:61)
        at com.googlecode.aviator.AviatorEvaluator.newInstance(AviatorEvaluator.java:87)
        at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:423)
        at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:549)
        At xxxxxx…..
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.googlecode.aviator.exception.CompileExpressionErrorException: define class error
        at com.googlecode.aviator.code.asm.ASMCodeGenerator.getResult(ASMCodeGenerator.java:849)
        at com.googlecode.aviator.code.OptimizeCodeGenerator.getResult(OptimizeCodeGenerator.java:440)
        at com.googlecode.aviator.code.LambdaGenerator.getResult(LambdaGenerator.java:424)
        at com.googlecode.aviator.code.LambdaGenerator.getLmabdaBootstrap(LambdaGenerator.java:189)
        at com.googlecode.aviator.code.OptimizeCodeGenerator.onLambdaBodyEnd(OptimizeCodeGenerator.java:785)
        at com.googlecode.aviator.code.LambdaGenerator.onLambdaBodyEnd(LambdaGenerator.java:472)
        at com.googlecode.aviator.parser.ExpressionParser.ifStatement(ExpressionParser.java:1916)
        at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:1627)
        at com.googlecode.aviator.parser.ExpressionParser.statements(ExpressionParser.java:1853)
        at com.googlecode.aviator.parser.ExpressionParser.forStatement(ExpressionParser.java:1789)
        at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:1634)
        at com.googlecode.aviator.parser.ExpressionParser.statements(ExpressionParser.java:1853)
        at com.googlecode.aviator.parser.ExpressionParser.lambda(ExpressionParser.java:793)
        at com.googlecode.aviator.parser.ExpressionParser.fnStatement(ExpressionParser.java:1265)
        at com.googlecode.aviator.parser.ExpressionParser.statement(ExpressionParser.java:1656)
        at com.googlecode.aviator.parser.ExpressionParser.statements(ExpressionParser.java:1835)
        at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:1106)
        at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:1120)
        at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1494)
        at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1455)
        at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1413)
        at com.googlecode.aviator.AviatorEvaluatorInstance.loadInternalLibs(AviatorEvaluatorInstance.java:1029)
        at com.googlecode.aviator.AviatorEvaluatorInstance.loadLib(AviatorEvaluatorInstance.java:898)
        at com.googlecode.aviator.AviatorEvaluatorInstance.<init>(AviatorEvaluatorInstance.java:1072)
        at com.googlecode.aviator.AviatorEvaluator$StaticHolder.<clinit>(AviatorEvaluator.java:91)
        at com.googlecode.aviator.AviatorEvaluator$StaticHolder.access$000(AviatorEvaluator.java:90) 
        at com.googlecode.aviator.AviatorEvaluator.getInstance(AviatorEvaluator.java:101) 
        at com.googlecode.aviator.AviatorEvaluator.<clinit>(AviatorEvaluator.java:61) 
        at com.googlecode.aviator.AviatorEvaluator.newInstance(AviatorEvaluator.java:87) 
        at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:423) 
        at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:549) 
        At xxxxxx…..
        at android.os.AsyncTask$3.call(AsyncTask.java:394) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
        at java.lang.ClassLoader.defineClass(ClassLoader.java:517)
        at com.googlecode.aviator.parser.AviatorClassLoader.defineClass(AviatorClassLoader.java:32)
```

**Comment by hsluoyz** [comment]
Asked here: https://github.com/killme2008/aviatorscript/issues/403

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@chancyWu Can you test your application by using this version [feat/android](https://github.com/tangyang9464/jcasbin/tree/feat/android). You just need to use ``mvn install`` to package

**Comment by chancyWu** [comment]
@tangyang9464  android can use the release, the issue is also fixed with the feat/android branch.

**Comment by tangyang9464** [comment]
@chancyWu thanks.I'll make a PR to update version.
