### ISSUE TITLE
calling enforce with group of grants feature does not work

### ISSUE THREAD

**Issue by zamrokk** [casbin/jcasbin#25]
Calling function com.se.datahub.main.CoreEnforcer.enforce(CoreEnforcer.java:345) with arguments : [alice, data3, read]   ends with error below :

```cmd
2019-04-19 14:24:58.543  INFO 4856 --- [io-8080-exec-10] org.casbin.jcasbin                       : Policy Rule: [alice, data1, read]
2019-04-19 14:24:58.543  INFO 4856 --- [io-8080-exec-10] org.casbin.jcasbin                       : Result: false
2019-04-19 14:24:58.543  INFO 4856 --- [io-8080-exec-10] org.casbin.jcasbin                       : Policy Rule: [bob, data2, write]
2019-04-19 14:24:58.543  INFO 4856 --- [io-8080-exec-10] org.casbin.jcasbin                       : Result: false
2019-04-19 14:24:58.543  INFO 4856 --- [io-8080-exec-10] org.casbin.jcasbin                       : Policy Rule: [data2_admin, data2, read]
2019-04-19 14:24:58.543  INFO 4856 --- [io-8080-exec-10] org.casbin.jcasbin                       : Result: false
2019-04-19 14:24:58.543  INFO 4856 --- [io-8080-exec-10] org.casbin.jcasbin                       : Policy Rule: [data2_admin, data2, write]
2019-04-19 14:24:58.543  INFO 4856 --- [io-8080-exec-10] org.casbin.jcasbin                       : Result: false
2019-04-19 14:24:58.543  INFO 4856 --- [io-8080-exec-10] org.casbin.jcasbin                       : Policy Rule: [data2_admin, datagroup, read]
2019-04-19 14:24:58.546 ERROR 4856 --- [io-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.googlecode.aviator.exception.ExpressionRuntimeException: Execute expression error] with root cause

java.lang.IllegalArgumentException: Wrong number of args (1) passed to: g3
	at com.googlecode.aviator.runtime.function.AbstractFunction.throwArity(AbstractFunction.java:19) ~[aviator-4.1.2.jar:na]
	at com.googlecode.aviator.runtime.function.AbstractFunction.call(AbstractFunction.java:47) ~[aviator-4.1.2.jar:na]
	at Script_1555676698541_2/1743385755.execute0(Unknown Source) ~[na:na]
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:72) ~[aviator-4.1.2.jar:na]
	at com.se.datahub.main.CoreEnforcer.enforce(CoreEnforcer.java:345) ~[classes/:na]
	at com.se.datahub.rest.EnforcementController.enforce(EnforcementController.java:21) ~[classes/:na]
```

**Comment by zamrokk** [comment]
model is
````
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _
g3 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && g3(r.act == p.act)
````

**Comment by zamrokk** [comment]
policies are :  

````
p, alice, data1,   read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write
g, alice, data2_admin
g2, data3, datagroup
p, data2_admin, datagroup, read
g3, read, admin
g3, write, admin
p, carole, data1, admin
````

**Comment by hsluoyz** [comment]
@zamrokk your model matcher is wrong: ``g3(r.act == p.act)``, you should provide 2 args for g3, current is one boolean.

**Comment by zamrokk** [comment]
You are right, it is what is happening when you do a live coding during a meeting you are the presenter XD  !

**Comment by zamrokk** [comment]
@hsluoyz , btw did you had time to see this issue here with the tenants ?https://github.com/casbin/jcasbin/issues/18

**Comment by hsluoyz** [comment]
I will take a look now.
