### ISSUE TITLE
jcasbin use aviator 5.x has Concurrency issues

### ISSUE THREAD

**Issue by shijianjs** [casbin/jcasbin#292]
## Version
- Have validation aviator 5.3.1、5.3.0、5.2.7、5.1.4、5.0.1；
- jcasbin version: 1.27.0
- jdbc-adapter: 2.3.2

## Exception info

```log
11:10:22.041 [pool-1-thread-1] INFO org.casbin.jcasbin - Request: user1029, avatar-ci:JenkinsTemplate, findAll ---> true
11:10:22.043 [pool-1-thread-15] INFO org.casbin.jcasbin - Request: user1029, avatar-ci:MultiCluster, create ---> false
11:10:22.049 [pool-1-thread-15] INFO org.casbin.jcasbin - Request: user1029, avatar-ci:EnvironmentManage, helmApplyNamespace ---> true
11:10:22.057 [pool-1-thread-13] INFO org.casbin.jcasbin - Request: user1029, avatar-ci:ApplicationManage, update ---> true
11:10:22.058 [pool-1-thread-15] INFO org.casbin.jcasbin - Request: user1029, avatar-ci:EnvironmentManage, findAll ---> true
执行异常出错：counter=6
com.googlecode.aviator.exception.ExpressionRuntimeException: <Nil, null> is not a boolean value
	at com.googlecode.aviator.runtime.type.AviatorObject.booleanValue(AviatorObject.java:223)
	at Script_1661915421986_1.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:65)
	at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:136)
	at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:519)
	at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:631)
	at com.fingard.rdc.avatar.auth.casbin.CasbinTest.lambda$parallelTest$5(CasbinTest.java:98)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

        11:10:22.067 [pool-1-thread-10] INFO org.casbin.jcasbin - Request: user1029, avatar-ci:MultiCluster, create ---> false
11:10:22.067 [pool-1-thread-9] INFO org.casbin.jcasbin - Request: user1029, avatar-ci:EnvironmentManage, delete ---> true
11:10:22.073 [pool-1-thread-6] INFO org.casbin.jcasbin - Request: user1029, avatar-ci:JenkinsTemplate, create ---> true

```

## model.conf
```conf
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act  || g(r.sub, "administrator") || r.sub == "admin"

```

## test code
```java
package com.fingard.rdc.avatar.auth.casbin;

import cn.hutool.core.util.RandomUtil;
import cn.hutool.core.util.StrUtil;
import com.fingard.rdc.avatar.auth.config.casbin.CasbinEnforcerConfig;
import com.fingard.rdc.avatar.auth.config.casbin.CasbinProperties;
import com.fingard.rdc.avatar.auth.config.casbin.EnforcerExt;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import lombok.val;
import org.jetbrains.annotations.NotNull;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;
import java.util.stream.Collectors;

public class CasbinTestGithub {

    @Test
    private static EnforcerExt getEnforcer() throws Exception {
        final HikariConfig hikariConfig = new HikariConfig();
        hikariConfig.setJdbcUrl("jdbc:postgresql://*****:***/avatar_dev_auth?stringtype=unspecified");
        hikariConfig.setUsername("******");
        hikariConfig.setPassword("******");
        final EnforcerExt enforcer = new CasbinEnforcerConfig().enforcer(new CasbinProperties(), new HikariDataSource(hikariConfig));
        return enforcer;
    }



    @Test
    public void parallelTest() throws Exception{
        val enforcer = getEnforcer();
        System.out.println("==================");
        System.out.println("==================");
        System.out.println("==================");
        final List<List<String>> data = getData();
        System.out.println(data);
        val threadPool = Executors.newCachedThreadPool();
        val latch = new CountDownLatch(1);
        val counter = new AtomicInteger();
        val threads = 20;
        final AtomicReference<Exception> reference = new AtomicReference<>();
        for (int i = 0; i < threads; i++) {
            threadPool.execute(()->{
                try {
                    while (true){
                        val authData = data.get(RandomUtil.randomInt(data.size()));
                        enforcer.enforce(authData.get(0),authData.get(1),authData.get(2));
                        counter.incrementAndGet();
                    }
                }catch (Exception e){
                    System.out.println("执行异常出错：counter="+counter.get());
                    e.printStackTrace();
                    reference.set(e);
                    latch.countDown();
                }
            });
        }
        latch.await();
        throw reference.get();
    }

    @NotNull
    private static List<List<String>> getData() {
        String dataStr  = " user1029, avatar-ci:MultiCluster, findPage ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, findPage ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, create ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, update ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, delete ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, get ---> true\n" +
           " user1029, avatar-ci:Navigation, getEnvironmentAllUrls ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, helmApplyNamespace ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, deleteHelmEnvironment ---> false\n" +
           " user1029, avatar-ci:EnvironmentManage, generateHelmValuesYaml ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, environmentManifest ---> true\n" +
           " user1029, avatar-ci:ApplicationManage, findAll ---> true\n" +
           " user1029, avatar-ci:ApplicationManage, update ---> true\n" +
           " user1029, avatar-ci:ApplicationManage, delete ---> true\n" +
           " user1029, avatar-ci:ApplicationManage, getJenkinsPipeline ---> true\n" +
           " user1029, avatar-ci:JenkinsTemplate, create ---> true\n" +
           " user1029, avatar-ci:JenkinsTemplate, findAll ---> true\n" +
           " user1029, avatar-ci:JenkinsTemplate, create ---> true\n" +
           " user1029, avatar-ci:JenkinsTemplate, get ---> true\n" +
           " user1029, avatar-ci:JenkinsTemplate, update ---> true\n" +
           " user1029, avatar-ci:JenkinsTemplate, delete ---> true\n" +
           " user1029, avatar-ci:NodeManage, findAll ---> true\n" +
           " user1029, avatar-ci:NodeManage, create ---> true\n" +
           " user1029, avatar-ci:NodeManage, update ---> true\n" +
           " user1029, avatar-ci:NodeManage, delete ---> true\n" +
           " user1029, avatar-ci:NodeManage, webshell ---> false\n" +
           " user1029, avatar-ci:NodeLimit, findAll ---> false\n" +
           " user1029, avatar-ci:NodeLimit, create ---> true\n" +
           " user1029, avatar-ci:NodeLimit, update ---> true\n" +
           " user1029, avatar-ci:NodeLimit, delete ---> true\n" +
           " user1029, avatar-ci:GlobalConfig, findAll ---> true\n" +
           " user1029, avatar-ci:GlobalConfig, save ---> true\n" +
           " user1029, avatar-ci:GlobalConfig, recoverSuper ---> true\n" +
           " user1029, avatar-ci:MultiCluster, delete ---> false\n" +
           " user1029, avatar-ci:MultiCluster, findAll ---> false\n" +
           " user1029, avatar-ci:MultiCluster, create ---> false\n" +
           " user1029, avatar-ci:MultiCluster, update ---> false\n" +
           " user1029, avatar-ci:EnvironmentManage, findAll ---> true\n" +
           "user1029, avatar-ci:MultiCluster, findPage ---> true\n" +
           "user1029, avatar-ci:EnvironmentManage, findPage ---> true\n" +
           "user1029, avatar-ci:EnvironmentManage, create ---> true\n" +
           "user1029, avatar-ci:EnvironmentManage, update ---> true\n" +
           "user1029, avatar-ci:EnvironmentManage, delete ---> true\n" +
           "user1029, avatar-ci:EnvironmentManage, get ---> true\n" +
           "user1029, avatar-ci:Navigation, getEnvironmentAllUrls ---> true\n" +
           "user1029, avatar-ci:EnvironmentManage, helmApplyNamespace ---> true\n" +
           "user1029, avatar-ci:EnvironmentManage, deleteHelmEnvironment ---> false\n" +
           "user1029, avatar-ci:EnvironmentManage, generateHelmValuesYaml ---> true\n" +
           "user1029, avatar-ci:EnvironmentManage, environmentManifest ---> true\n" +
           "user1029, avatar-ci:ApplicationManage, findAll ---> true\n" +
           "user1029, avatar-ci:ApplicationManage, update ---> true\n" +
           "user1029, avatar-ci:ApplicationManage, delete ---> true\n" +
           "user1029, avatar-ci:ApplicationManage, getJenkinsPipeline ---> true\n" +
           "user1029, avatar-ci:JenkinsTemplate, create ---> true\n" +
           "user1029, avatar-ci:JenkinsTemplate, findAll ---> true\n" +
           "user1029, avatar-ci:JenkinsTemplate, create ---> true\n" +
           "user1029, avatar-ci:JenkinsTemplate, get ---> true\n" +
           "user1029, avatar-ci:JenkinsTemplate, update ---> true\n" +
           "user1029, avatar-ci:JenkinsTemplate, delete ---> true\n" +
           "user1029, avatar-ci:NodeManage, findAll ---> true\n" +
           "user1029, avatar-ci:NodeManage, create ---> true\n" +
           "user1029, avatar-ci:NodeManage, update ---> true\n" +
           "user1029, avatar-ci:NodeManage, delete ---> true\n" +
           "user1029, avatar-ci:NodeManage, webshell ---> false\n" +
           "user1029, avatar-ci:NodeLimit, findAll ---> false\n" +
           "user1029, avatar-ci:NodeLimit, create ---> true\n" +
           "user1029, avatar-ci:NodeLimit, update ---> true\n" +
           "user1029, avatar-ci:NodeLimit, delete ---> true\n" +
           "user1029, avatar-ci:GlobalConfig, findAll ---> true\n" +
           "user1029, avatar-ci:GlobalConfig, save ---> true\n" +
           "user1029, avatar-ci:GlobalConfig, recoverSuper ---> true\n" +
           "user1029, avatar-ci:MultiCluster, delete ---> false\n" +
           "user1029, avatar-ci:MultiCluster, findAll ---> false\n" +
           "user1029, avatar-ci:MultiCluster, create ---> false\n" +
           "user1029, avatar-ci:MultiCluster, update ---> false\n" +
           "user1029, avatar-ci:EnvironmentManage, findAll ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, findAll ---> true\n" +
           " user1029, avatar-ci:Navigation, getEnvironmentAllUrls ---> true\n" +
           " user1029, avatar-ci:environment/psq-test-001, QUERY ---> true\n" +
           "user1029, avatar-ci:EnvironmentManage, findAll ---> true\n" +
           "user1029, avatar-ci:MultiCluster, findPage ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, findAll ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, findAll ---> true\n" +
           " user1029, avatar-ci:Navigation, getEnvironmentAllUrls ---> true\n" +
           "user1029, avatar-ci:environment/psq-test-001, QUERY ---> true\n" +
           "user1029, avatar-ci:EnvironmentManage, findAll ---> true\n" +
           "user1029, avatar-ci:MultiCluster, findPage ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, findAll ---> true\n" +
           " user1029, avatar-ci:EnvironmentManage, findAll ---> true\n" +
           " user1029, avatar-ci:Navigation, getEnvironmentAllUrls ---> true\n" +
           "user1029, avatar-ci:environment/psq-test-001, QUERY ---> true";

        val data = StrUtil.split(dataStr,'\n').stream()
                .map(s->s.trim())
                .map(s->StrUtil.removeSuffix(s,"true"))
                .map(s->StrUtil.removeSuffix(s,"false"))
                .map(s->StrUtil.removeSuffix(s," ---> "))
                .map(s->StrUtil.split(s,',').stream().map(s1 -> s1.trim()).collect(Collectors.toList()))
                // .peek(s-> System.out.println(s))
                .collect(Collectors.toList());
        return data;
    }
}

```

**Comment by hsluoyz** [comment]
@seriouszyx @imp2002 

/cc @tangyang9464

**Comment by damienmiheev** [comment]
I'm struggling with a same issue. jcasbin 1.28.1

My model:
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
```

Even though i'm using synchronised enforcer, Exception is throwing periodically on async request to enforcer.
Would be nice if you can prioritise this bug.

**Comment by hsluoyz** [comment]
@imp2002
