### ISSUE TITLE
get 'define class error' for first enforcement

### ISSUE THREAD

**Issue by lissali** [casbin/jcasbin#345]
this is my model:

m.addDef("r", "r", "sub, dom, obj, act");
m.addDef("p", "p", "sub, dom, obj, act");
m.addDef("g", "g", "_, _, _");
m.addDef("e", "e", "some(where (p.eft == allow))");
m.addDef("m", "m", "g(r.sub, p.sub, r.dom) && keyMatch(r.dom, p.dom) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)");

when try to enforce for the first time, get the error : define class error

com.googlecode.aviator.exception.CompileExpressionErrorException: define class error
at com.googlecode.aviator.code.asm.ASMCodeGenerator.getResult(ASMCodeGenerator.java:819)
at com.googlecode.aviator.code.OptimizeCodeGenerator.getResult(OptimizeCodeGenerator.java:416)
at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:976)
at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:981)
at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1365)
at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1328)
at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:492)
at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:632)

**Comment by hsluoyz** [comment]
Closed as stale
