### ISSUE TITLE
[Bug] ConcurrentModificationException breaks Enforcer when calling Enforce()

### ISSUE THREAD

**Issue by ArthurBalabushko** [casbin/jcasbin#361]
it is similar to this issue https://github.com/casbin/casbin/issues/1318

casbin-spring-boot-starter: 1.1.0
useSyncedEnforcer: false
storeType: jdbc
enableWatcher: false
`AddNamedMatchingFunc(`): KeyMatch4

model.conf
```
[request_definition]
r = sub, obj

[policy_definition]
p = sub, obj, eft

[role_definition]
g = _, _

[policy_effect]
e = !some(where (p.eft == deny))

[matchers]
m = r.sub == p.sub && g(r.obj, p.obj)
```

exception:
```
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1511)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1544)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1542)
	at org.casbin.jcasbin.rbac.DefaultRoleManager.getRole(DefaultRoleManager.java:111)
	at org.casbin.jcasbin.rbac.DefaultRoleManager.hasLink(DefaultRoleManager.java:186)
	at org.casbin.jcasbin.rbac.DomainManager.hasLink(DomainManager.java:148)
	at org.casbin.jcasbin.util.BuiltInFunctions$GenerateGFunctionClass$1.variadicCall(BuiltInFunctions.java:378)
	at com.googlecode.aviator.runtime.function.AbstractVariadicFunction.call(AbstractVariadicFunction.java:71)
	at Script_1695382193455_59.execute0(Script_1695382193455_59:1)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:44)
	at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:237)
	at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:540)
	at org.casbin.jcasbin.main.CoreEnforcer.enforce(CoreEnforcer.java:646)
```

**Comment by praneethc18** [comment]
can someone help with this, I faced the same issue with keyMatch4

**Comment by hsluoyz** [comment]
@amikecoXu
