### ISSUE TITLE
Multi-line mode Matcher not work

### ISSUE THREAD

**Issue by GYWang1983** [casbin/jcasbin#96]
If appending '\\' at the end of Line, an ExpressionSyntaxErrorException occurs

```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act, eft

[role_definition]
g = _, _,; user group
g2 = _, _, _ ; group role
g3 = _, _, _ ; resource group

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (g(r.sub, p.sub) || g2(r.sub, p.sub, r.dom)) && (keyMatch(r.obj, p.obj) || g3(r.obj, p.obj, r.dom)) \
    && (p.dom == 'public' || r.dom == p.dom) && keyMatch(r.act, p.act)
```

```exception
Caused by: com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error:Unexpect token '\' at 100, current token: [type='Char',lexeme='\',index=100]. Parsing expression: `(g(r_sub, p_sub) || g2(r_sub, p_sub, r_dom)) && (keyMatch(r_obj, p_obj) || g3(r_obj, p_obj, r_dom)) \^^`
	at com.googlecode.aviator.parser.ExpressionParser.reportSyntaxError(ExpressionParser.java:765)
	at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:791)
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:673)
	at com.googlecode.aviator.AviatorEvaluatorInstance.access$000(AviatorEvaluatorInstance.java:109)
	at com.googlecode.aviator.AviatorEvaluatorInstance$2.call(AviatorEvaluatorInstance.java:641)
	at com.googlecode.aviator.AviatorEvaluatorInstance$2.call(AviatorEvaluatorInstance.java:638)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:648)
```

**Comment by hsluoyz** [comment]
@tldyl

**Comment by hsluoyz** [comment]
@tldyl merged, please make a new release.
